"""Integration: corrupt PDF → document reaches 'failed', no spans persisted."""

from __future__ import annotations

import pytest
from sqlalchemy import text


_CORRUPT_PDF = (
    b"%PDF-1.4\n"
    b"\x00\x00\x00\x00\x00GARBAGE_NOT_A_VALID_PDF_BODY\x00\x00"
    b"\xff\xfe\xfd\xfc" * 10
)


@pytest.mark.asyncio
async def test_corrupt_pdf_fails_cleanly(
    ocr_ingest_service,
    db_session,
    tmp_uploads_dir,
    cleanup_documents_and_jobs,
):
    """A corrupt PDF must transition to 'failed' with a typed error_code.

    Acceptance criteria:
    - document.status = 'failed'
    - document.error_code is set (non-null)
    - No spans are persisted for the document
    - Queue is not poisoned (job fails with retryable=False so it won't loop)
    """
    from io import BytesIO
    from fastapi import UploadFile

    upload = UploadFile(filename="corrupt.pdf", file=BytesIO(_CORRUPT_PDF))
    result = await ocr_ingest_service.upload(upload)
    assert result.was_new
    doc_id = result.document_id

    from app.core.errors import IngestError

    with pytest.raises(IngestError) as exc_info:
        await ocr_ingest_service.ocr_document(doc_id)
    assert exc_info.value.retryable is False, (
        f"Corrupt-file errors must have retryable=False; got code={exc_info.value.code}"
    )

    # Document must be marked failed with a typed code
    doc_row = await db_session.execute(
        text("SELECT status, error_code FROM app.documents WHERE id = :id"),
        {"id": doc_id},
    )
    doc = doc_row.fetchone()
    assert doc.status == "failed", f"Expected failed, got {doc.status}"
    assert doc.error_code is not None, "error_code must be set on failure"

    # No spans persisted
    spans_q = await db_session.execute(
        text(
            """
            SELECT COUNT(*) AS n
              FROM app.spans s
              JOIN app.pages p ON p.id = s.page_id
             WHERE p.document_id = :d
            """
        ),
        {"d": doc_id},
    )
    assert spans_q.scalar_one() == 0, "No spans should be persisted for a corrupt file"


@pytest.mark.asyncio
async def test_corrupt_pdf_via_fixture(
    ocr_fixture_docs,
    ocr_ingest_service,
    db_session,
    tmp_uploads_dir,
    cleanup_documents_and_jobs,
):
    """The corrupt.pdf generated by scripts/generate_fixtures.py also fails cleanly."""
    from io import BytesIO
    from fastapi import UploadFile
    from app.core.errors import IngestError

    pdf_path = ocr_fixture_docs / "corrupt.pdf"
    upload = UploadFile(filename="corrupt.pdf", file=BytesIO(pdf_path.read_bytes()))
    result = await ocr_ingest_service.upload(upload)
    doc_id = result.document_id

    with pytest.raises(IngestError) as exc_info:
        await ocr_ingest_service.ocr_document(doc_id)
    assert exc_info.value.retryable is False, (
        f"Corrupt-file errors must have retryable=False; got code={exc_info.value.code}"
    )

    doc_row = await db_session.execute(
        text("SELECT status FROM app.documents WHERE id = :id"), {"id": doc_id}
    )
    assert doc_row.scalar_one() == "failed"
